const {BASE_URL,ARTIFACT_DIR,artifact}=require('./config.cjs');
const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch();const ctx=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});
 await ctx.addInitScript(()=>{window.shareCalls=[];window.shareMode='ok';Object.defineProperty(navigator,'canShare',{configurable:true,value:()=>true});Object.defineProperty(navigator,'share',{configurable:true,value:async data=>{if(window.shareMode!=='ok')throw new DOMException('sharing unavailable',window.shareMode);window.shareCalls.push({name:data.files[0].name,type:data.files[0].type,size:data.files[0].size});}});});
 const p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());await p.goto(BASE_URL);await p.waitForFunction(()=>!document.querySelector('#go').disabled);
 const fixture=Buffer.from(await p.evaluate(()=>{const c=document.createElement('canvas');c.width=540;c.height=4000;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,540,4000);x.fillStyle='#172c43';x.font='22px sans-serif';for(let y=35;y<4000;y+=45)x.fillText('Article line '+y+' — a mobile preview.',20,y);return c.toDataURL().split(',')[1];}),'base64');
 await p.locator('#file').setInputFiles({name:'mobile.png',mimeType:'image/png',buffer:fixture});await p.waitForFunction(()=>!document.querySelector('#editor').hidden);await p.waitForTimeout(350);
 assert.equal(await p.locator('.source-panel,#sourceTab,#editTab').count(),0);assert(await p.locator('.workspace').isVisible());assert(await p.locator('.setup-panel').isHidden());assert(await p.locator('#mobileDock').isVisible());assert.equal(await p.locator('#position').evaluate(e=>e.closest('#mobileDock')?.id),'mobileDock');
 await p.locator('#dockAdd').click();assert.equal(await p.locator('.thumb').count(),2);assert.equal(await p.locator('#position').inputValue(),'1350');
 await p.locator('#position').fill('800');await p.locator('#zoom').fill('100');await p.locator('#editorCanvas').scrollIntoViewIfNeeded();await p.waitForTimeout(350);
 const cdp=await ctx.newCDPSession(p),r=await p.locator('#editorCanvas').boundingBox();const center={x:r.x+r.width/2,y:r.y+r.height/2},touch=(dx,id)=>({x:center.x+dx,y:center.y,id});
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[touch(-40,0),touch(40,1)]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[touch(-48,0),touch(48,1)]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.waitForTimeout(100);
 assert(Math.abs(+await p.locator('#zoom').inputValue()-120)<=1);assert(Math.abs(+await p.locator('#position').inputValue()-(800+1350/2*(1-1/1.2)))<3);
 await p.locator('#dockUndo').click();assert.equal(await p.locator('#zoom').inputValue(),'100');assert.equal(await p.locator('#position').inputValue(),'800');
 // Lock prevents all accidental edits and survives local session saving.
 await p.locator('#lockFraming').click();assert(await p.locator('#zoom').isDisabled());assert(await p.locator('#dockCut').isDisabled());const locked=await p.locator('#editorCanvas').evaluate(c=>c.toDataURL());await p.locator('#editorCanvas').scrollIntoViewIfNeeded();const r2=await p.locator('#editorCanvas').boundingBox();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:r2.x+100,y:r2.y+100}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:r2.x+100,y:r2.y+50}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(await p.locator('#editorCanvas').evaluate(c=>c.toDataURL()),locked);
 await p.waitForFunction(()=>document.querySelector('#saveStatus').textContent==='Saved on this device');await p.reload();await p.waitForFunction(()=>document.querySelector('#saveStatus').textContent==='Saved session restored');assert.equal(await p.locator('#lockFraming').getAttribute('aria-pressed'),'true');await p.locator('#lockFraming').click();
 // Full-screen cut mode isolates controls, reserves a fixed action footer, magnifies edges.
 await p.locator('#dockCut').click();assert(await p.locator('body').evaluate(e=>e.classList.contains('mobile-cut')));assert.equal(await p.locator('#editor').getAttribute('aria-modal'),'true');assert(await p.locator('#mobileDock').evaluate(e=>e.inert));
 await p.locator('#cutTop').fill('220');await p.locator('#cutBottom').fill('400');assert(await p.locator('#edgeMagnifier').isVisible());
 const limits=await p.evaluate(()=>{const r=s=>{const a=document.querySelector(s).getBoundingClientRect();return {y:a.y,b:a.bottom,h:a.height,w:a.width}};return {h:innerHeight,editor:r('#editor'),canvas:r('#editorCanvas'),apply:r('#applyCut'),cancel:r('#cancelCut'),overflow:document.documentElement.scrollWidth>innerWidth};});assert(limits.apply.b<=limits.h+1);assert(limits.cancel.b<=limits.h+1);assert(limits.canvas.y>=0);assert(limits.canvas.b<limits.apply.y);assert(!limits.overflow);
 await p.screenshot({path:artifact('newsgram-mobile-cut.png')});await p.locator('#applyCut').click();assert(await p.locator('#undoToast').isVisible());assert(await p.locator('#mobileDock').isVisible());assert(!(await p.locator('#mobileDock').evaluate(e=>e.inert)));await p.locator('#toastUndo').click();assert(await p.locator('#editCuts').isHidden());
 await p.locator('#remove').click();assert.equal(await p.locator('.thumb').count(),1);await p.locator('#toastUndo').click();assert.equal(await p.locator('.thumb').count(),2);
 // Native-share path uses an already-prepared PNG file and doesn't post anywhere itself.
 await p.locator('#dockExport').click();await p.waitForFunction(()=>!document.querySelector('#shareSelected').disabled);assert.equal(await p.locator('#shareSelected').textContent(),'Share selected PNG');await p.locator('#shareSelected').click();assert.equal(await p.evaluate(()=>shareCalls.length),1);const shared=await p.evaluate(()=>shareCalls[0]);assert.equal(shared.type,'image/png');assert(shared.size>1000);assert(shared.name.endsWith('.png'));
 // Cancellation doesn't download; a blocked share offers explicit download fallback.
 await p.evaluate(()=>shareMode='AbortError');await p.locator('#dockExport').click();await p.waitForFunction(()=>!document.querySelector('#shareSelected').disabled);await p.locator('#shareSelected').click();assert((await p.locator('#exportHint').textContent()).includes('cancelled'));await p.locator('#closeExport').click();
 await p.evaluate(()=>shareMode='NotAllowedError');await p.locator('#dockExport').click();await p.waitForFunction(()=>!document.querySelector('#shareSelected').disabled);await p.locator('#shareSelected').click();assert(await p.locator('#saveSelected').isVisible());const d=p.waitForEvent('download');await p.locator('#saveSelected').click();assert((await(await d).suggestedFilename()).endsWith('.png'));
 await p.evaluate(()=>Object.defineProperty(navigator,'canShare',{value:()=>false}));await p.locator('#dockExport').click();await p.waitForFunction(()=>!document.querySelector('#shareSelected').disabled);assert.equal(await p.locator('#shareSelected').textContent(),'Save selected PNG');await p.locator('#closeExport').click();
 await p.locator('#mobileSetup').click();assert(await p.locator('.setup-panel').isVisible());await p.locator('#mobileSetup').click();assert(await p.locator('.setup-panel').isHidden());
 await p.waitForTimeout(350);await p.screenshot({path:artifact('newsgram-mobile-editor.png')});

 assert.deepEqual(errors,[]);await browser.close();console.log('PASS: single mobile editor, immediate Add, bottom controls, anchored pinch+undo, saved lock, focused cuts, magnifier, safe pinned buttons, toast undo, native share/cancel/blocked/fallback, settings access; no JS errors.');
})().catch(e=>{console.error(e);process.exit(1)});
