const {BASE_URL,ARTIFACT_DIR,artifact}=require('./config.cjs');
const {savedSource}=require('./helpers.cjs');
const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
(async()=>{
 const browser=await chromium.launch(),context=await browser.newContext({viewport:{width:1440,height:1100}}),p=await context.newPage(),errors=[],external=[],dialogs=[];
 p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith(BASE_URL+'/'))external.push(r.url());});
 p.on('dialog',d=>{dialogs.push(d.message());d.accept();});
 const fixture=name=>path.join(__dirname,'fixtures',name);
 const ready=()=>p.waitForFunction(()=>!document.querySelector('#go').disabled);
 const hash=()=>p.locator('#editorCanvas').evaluate(c=>c.toDataURL());
 const upload=async name=>{await p.locator('#file').setInputFiles(fixture(name));await p.waitForFunction(()=>!document.querySelector('#pdfImportGo').hidden&&!document.querySelector('#pdfImportGo').disabled);};
 const finish=async()=>{await p.locator('#pdfImportGo').click();await ready();assert((await p.locator('#status').textContent()).startsWith('PDF loaded'));};
 const pixel=(x,y)=>p.locator('#editorCanvas').evaluate((c,[x,y])=>[...c.getContext('2d').getImageData(x,y,1,1).data].slice(0,3),[x,y]);
 const saved=async()=>{await p.waitForFunction(()=>document.querySelector('#saveStatus').textContent==='Saved on this device');return p.evaluate(()=>new Promise(resolve=>{const r=indexedDB.open('newsgram-studio',1);r.onsuccess=()=>{const db=r.result,q=db.transaction('session').objectStore('session').get('current');q.onsuccess=()=>{resolve({meta:q.result.meta,highlights:q.result.highlights,type:q.result.blob.type});db.close();};};}));};
 await p.goto(BASE_URL);await ready();assert((await p.locator('#file').getAttribute('accept')).includes('application/pdf'));
 // Rendering really uses the bundled PDF.js worker, fonts and assets with the network offline.
 await context.setOffline(true);await upload('layout.pdf');assert.equal(await p.locator('#pdfTo').inputValue(),'3');await finish();
 const originalSource=await savedSource(p);assert.deepEqual([originalSource.width,originalSource.height],[1080,2840]);assert((await p.locator('#documentInfo').textContent()).includes('3 PDF pages'));assert.equal(await p.locator('#sourceScroll,#shotImg').count(),0);
 assert.deepEqual(await pixel(5,5),[31,46,61]);const original=await hash();const record=await saved();assert.equal(record.type,'image/png');assert.deepEqual(record.meta.pdfPages.map(p=>p.page),[1,2,3]);assert.deepEqual(record.meta.pdfPages.map(p=>p.start),[0,1400,2120]);
 // Add an independent highlight on the scanned page through the continuous source, not text extraction.
 await p.locator('#addNext').click();assert.equal(await p.locator('#position').inputValue(),'1350');assert.equal(await p.locator('.thumb').count(),2);await p.locator('#position').fill('1400');const second=await hash();assert.deepEqual(await pixel(5,5),[20,76,153]);
 await p.locator('#highlightSelect').selectOption('1');assert.equal(await hash(),original);await p.locator('#highlightSelect').selectOption('2');assert.equal(await hash(),second);
 // Existing cuts, history and framing operate on the exact same rendered bitmap.
 await p.locator('#cutSection').click();await p.locator('#cutTop').fill('100');await p.locator('#cutBottom').fill('250');await p.locator('#cutDivider').uncheck();await p.locator('#applyCut').click();const cutHash=await hash();assert.notEqual(cutHash,second);await p.locator('#undo').click();assert.equal(await hash(),second);await p.locator('#redo').click();assert.equal(await hash(),cutHash);
 await p.locator('#mobileSetup').click();for(const [ratio,height] of [['1:1',1080],['9:16',1920],['4:5',1350]]){await p.locator(`[data-ratio="${ratio}"]`).click();assert.deepEqual(await p.locator('#editorCanvas').evaluate(c=>[c.width,c.height]),[1080,height]);}
 const png=p.waitForEvent('download');await p.locator('#downloadOne').click();const download=await png;assert.equal(download.suggestedFilename(),'layout-highlight-02.png');const stream=await download.createReadStream(),chunks=[];for await(const chunk of stream)chunks.push(chunk);const pngBytes=Buffer.concat(chunks);assert.equal(pngBytes.readUInt32BE(16),1080);assert.equal(pngBytes.readUInt32BE(20),1350);
 const zip=p.waitForEvent('download');await p.locator('#downloadAll').click();assert((await zip).suggestedFilename().endsWith('.zip'));await saved();
 // Only the PNG plus page boundaries are saved. A reload needs no PDF library/network rendering.
 await context.setOffline(false);await p.reload();await p.waitForFunction(()=>document.querySelector('#saveStatus').textContent==='Saved session restored');assert.equal(await hash(),cutHash);assert((await p.locator('#documentInfo').textContent()).includes('3 PDF pages'));await context.setOffline(true);
 // Invalid files, cancellation at the chooser, password prompt and early load preserve current work.
 await upload('layout.pdf');await p.locator('#pdfCancel').click();await ready();assert.equal(await hash(),cutHash);
 await p.locator('#file').setInputFiles({name:'bad.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.7\nnot a valid document')});await ready();assert((await p.locator('#status').textContent()).includes('Could not import PDF'));assert.equal(await hash(),cutHash);
 await p.locator('#file').setInputFiles(fixture('protected.pdf'));await p.locator('#pdfPassword').waitFor({state:'visible'});await p.locator('#pdfPassword').fill('wrong');await p.locator('#pdfUnlock').click();await p.waitForFunction(()=>document.querySelector('#pdfPasswordMessage').textContent.includes('not accepted'));await p.locator('#pdfCancel').click();await ready();assert.equal(await hash(),cutHash);assert.equal(await p.locator('#pdfPassword').inputValue(),'');
 await p.locator('#file').setInputFiles(fixture('layout.pdf'));await p.locator('#pdfCancel').click();await ready();assert.equal(await hash(),cutHash);
 // Cancellation during asynchronous image encoding cannot adopt a partial source.
 await upload('layout.pdf');await p.evaluate(()=>{window.oldToBlob=HTMLCanvasElement.prototype.toBlob;HTMLCanvasElement.prototype.toBlob=function(cb,...args){return window.oldToBlob.call(this,b=>setTimeout(()=>cb(b),this.height>2000?600:0),...args);};});await p.locator('#pdfImportGo').click();await p.waitForFunction(()=>document.querySelector('#pdfProgress').textContent.includes('Preparing the continuous source'));await p.locator('#pdfCancel').click();await ready();await p.evaluate(()=>{HTMLCanvasElement.prototype.toBlob=window.oldToBlob;delete window.oldToBlob;});assert.equal(await hash(),cutHash);
 // The file-size guard rejects before parsing and preserves existing work.
 await p.evaluate(()=>{const input=document.querySelector('#file'),dt=new DataTransfer();dt.items.add(new File([new Uint8Array(50*1024*1024+1)],'oversized.pdf',{type:'application/pdf'}));input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}));});await ready();assert((await p.locator('#status').textContent()).includes('50 MB'));assert.equal(await hash(),cutHash);
 // Locked PDFs can be opened locally without persisting the password or original PDF bytes.
 await p.locator('#file').setInputFiles(fixture('protected.pdf'));await p.locator('#pdfPassword').waitFor({state:'visible'});await p.locator('#pdfPassword').fill('test-password');await p.locator('#pdfUnlock').click();await p.waitForFunction(()=>!document.querySelector('#pdfImportGo').hidden);await finish();assert.equal(await p.locator('#pdfPassword').inputValue(),'');assert.equal((await saved()).type,'image/png');
 const protectedHash=await hash();
 await upload('too-tall.pdf');await p.locator('#pdfImportGo').click();await ready();assert((await p.locator('#status').textContent()).includes('too tall'));assert.equal(await hash(),protectedHash);
 // Long PDFs have a bounded, explicitly editable range and predictable quality reduction.
 await upload('long.pdf');assert.equal(await p.locator('#pdfTo').inputValue(),'20');await p.locator('#pdfTo').fill('21');assert(await p.locator('#pdfImportGo').isDisabled());await p.locator('#pdfFrom').fill('0');assert(await p.locator('#pdfImportGo').isDisabled());await p.locator('#pdfFrom').fill('6');await p.locator('#pdfTo').fill('25');await finish();
 const longSource=await savedSource(p),sizes=[longSource.width,longSource.height];assert(sizes[0]>=540&&sizes[0]<1080);assert(sizes[1]<=16000);assert(sizes[0]*sizes[1]<=12*1024*1024);assert.equal(longSource.meta.pdfPages.length,20);assert.equal(longSource.meta.pdfPages[0].page,6);assert((await p.locator('#status').textContent()).includes('sharper detail'));
 // Switching to a normal image clears PDF-specific navigation and saves as before.
 const image=Buffer.from(await p.evaluate(()=>{const c=document.createElement('canvas');c.width=540;c.height=2000;return c.toDataURL().split(',')[1];}),'base64');await p.locator('#file').setInputFiles({name:'image.png',mimeType:'image/png',buffer:image});await ready();assert(await p.locator('#documentInfo').isHidden());
 assert.deepEqual(external,[]);assert(!dialogs.some(t=>t.includes('JavaScript must not execute')));assert.deepEqual(errors,[]);
 // Phone dialogs, continuous scrolling, add, saved cut editing and rotation still work.
 const mobile=await browser.newContext({viewport:{width:320,height:568},hasTouch:true,isMobile:true}),q=await mobile.newPage();q.on('pageerror',e=>errors.push(e.message));await q.goto(BASE_URL);await q.waitForFunction(()=>!document.querySelector('#go').disabled);await q.locator('#file').setInputFiles(fixture('layout.pdf'));await q.waitForFunction(()=>!document.querySelector('#pdfImportGo').hidden);
 const bounds=await q.locator('#pdfCancel').boundingBox();assert(bounds.x>=0&&bounds.y>=0&&bounds.y+bounds.height<=568);assert(await q.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await q.locator('#pdfImportGo').click();await q.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('PDF loaded'));await q.locator('#dockAdd').click();assert.equal(await q.locator('#position').inputValue(),'1350');assert.equal(await q.locator('.thumb').count(),2);await q.locator('#dockCut').click();await q.setViewportSize({width:844,height:390});assert(await q.locator('body').evaluate(e=>e.classList.contains('mobile-cut')));await q.locator('#cancelCut').click();await q.waitForTimeout(350);await q.screenshot({path:artifact('pdf-mobile-editor.png')});
 assert.deepEqual(errors,[]);await browser.close();console.log('PASS: real offline PDF.js rendering; styled/scanned/rotated pages joined; PDF metadata and immediate continuation; independent highlights/cuts/ratios/PNG/ZIP; PNG-only persistence; protected/invalid/oversize-height PDFs and cancellation; bounded page ranges/adaptive resolution; image-upload cleanup; phone dialog and landscape tools; no external requests, PDF script execution or JS errors.');
})().catch(e=>{console.error(e);process.exit(1)});
