const {BASE_URL,ARTIFACT_DIR,artifact}=require('./config.cjs');
const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch();const p=await b.newPage({viewport:{width:1440,height:1100}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(BASE_URL);await p.waitForFunction(()=>!document.querySelector('#go').disabled);
const fixture=Buffer.from(await p.evaluate(()=>{const c=document.createElement('canvas');c.width=540;c.height=2200;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,540,2200);x.fillStyle='#222';x.font='22px sans-serif';x.fillText('Article preview',30,70);return c.toDataURL().split(',')[1];}),'base64');
const keys=['#url','#captureDetails','.formatbar','#go','main'];
for(const viewport of [{width:1440,height:1100},{width:390,height:844}]){await p.setViewportSize(viewport);assert(await p.locator('.stage-title').isHidden());assert(await p.locator('main').isHidden());assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:artifact(`newsgram-setup-${viewport.width}.png`),fullPage:true});}
let calls=0,params;await p.route('https://api.microlink.io/**',r=>{calls++;params=new URL(r.request().url()).searchParams;return r.fulfill({status:200,contentType:'image/png',body:fixture});});
await p.locator('#captureDetails summary').click();await p.locator('#width').selectOption('768');await p.locator('#area').selectOption('page');await p.locator('#stack').uncheck();await p.locator('#url').fill('https://example.com/article');await p.locator('#go').click();await p.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Captured'));assert.equal(params.get('viewport.width'),'768');assert.equal(params.get('screenshot.fullPage'),'true');assert(!params.has('styles'));assert.equal(await p.locator('#dismissOverlays').count(),0,'menu/dialog dismissal control is no longer offered');assert.equal(await p.locator('#includeLogo').isChecked(),true);assert.equal(await p.locator('#hideSocial').isChecked(),true);assert(params.get('scripts').includes('share'),'default capture script hides share widgets');assert(!params.get('scripts').includes('aria-expanded'),'capture no longer injects the menu-dismissal script');assert(!params.get('scripts').includes('data-newsgram-logo'),'Whole webpage keeps its original masthead instead of duplicating the logo');assert.equal(await p.locator('#captureDetails').getAttribute('open'),null);await p.setViewportSize({width:1440,height:1100});await p.locator('#mobileSetup').click();const y=await p.evaluate(keys=>keys.map(k=>document.querySelector(k).getBoundingClientRect().top),keys);assert(y.every((v,i)=>!i||v>y[i-1]),JSON.stringify(y));assert(await p.locator('.stage-title').isHidden());assert(await p.locator('#mobileSetup').isVisible());assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.locator('#mobileSetup').click();await p.setViewportSize({width:390,height:844});assert(await p.locator('main').isVisible());assert(await p.locator('.stage-title').isHidden());assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
const hash=await p.locator('#editorCanvas').evaluate(c=>c.toDataURL());await p.locator('#mobileSetup').click();await p.locator('#hideSocial').uncheck();assert(await p.locator('#captureChanges').isVisible());await p.locator('#hideSocial').check();assert(await p.locator('#captureChanges').isHidden());await p.locator('#width').selectOption('540');assert(await p.locator('#captureChanges').isVisible());assert.equal(calls,1);assert.equal(await p.locator('#editorCanvas').evaluate(c=>c.toDataURL()),hash);
await p.locator('#width').selectOption('768');assert(await p.locator('#captureChanges').isHidden());await p.locator('[data-ratio="1:1"]').click();assert(await p.locator('#captureChanges').isHidden());assert.equal(calls,1);
// Article-only capture carries the opt-in logo copier, which adds just the brand mark to the article.
const logoContext=await b.newContext(),logoPage=await logoContext.newPage();let articleParams,articleCalls=0;await logoPage.route('https://api.microlink.io/**',r=>{articleCalls++;articleParams=new URL(r.request().url()).searchParams;return r.fulfill({status:200,contentType:'image/png',body:fixture});});await logoPage.goto(BASE_URL);await logoPage.waitForFunction(()=>!document.querySelector('#go').disabled);await logoPage.locator('#url').fill('https://www.independent.com/2026/10/06/the-public-has-already-weighed-in-on-state-street/');await logoPage.locator('#go').click();await logoPage.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Captured'));assert.equal(articleParams.get('screenshot.element'),'article');assert.equal(articleCalls,1);assert(articleParams.get('scripts').includes('data-newsgram-logo'),'Article capture includes the logo-injection script');
const copied=await logoPage.evaluate(script=>{const header=document.createElement('header'),mark=document.createElement('a');header.style.cssText='position:fixed;left:0;top:0;z-index:99999;background:#fff';mark.className='site-logo';mark.setAttribute('aria-label','Santa Barbara Independent');mark.textContent='Santa Barbara Independent';header.append(mark);const article=document.createElement('article');article.style.cssText='position:fixed;left:0;top:80px;width:500px;height:500px';const share=document.createElement('div');share.className='share-buttons';const social=document.createElement('a');social.href='https://www.facebook.com/sharer/sharer.php';social.setAttribute('aria-label','Share on Facebook');social.textContent='Share';share.append(social);const keep=document.createElement('button');keep.textContent='Read more';const embed=document.createElement('iframe');embed.className='social-embed';article.append(share,keep,embed);document.body.prepend(header,article);(0,eval)(script);const copy=article.querySelector('[data-newsgram-logo]');return{found:!!copy,text:copy?.textContent.trim(),shareHidden:share.style.display==='none',keepVisible:keep.style.display!=='none',embedVisible:embed.style.display!=='none'};},articleParams.get('scripts'));assert.equal(copied.found,true);assert.equal(copied.text,'Santa Barbara Independent');assert.equal(copied.shareHidden,true,'share controls are hidden before capture');assert.equal(copied.keepVisible,true,'ordinary article controls are left intact');assert.equal(copied.embedVisible,true,'embedded social posts remain visible');await logoContext.close();
assert.deepEqual(errors,[]);console.log('PASS: capture settings, social-button hiding, Article-only logo inclusion, desktop/mobile layout and cache notice.');await b.close();})().catch(e=>{console.error(e);process.exit(1)});
