const {BASE_URL,ARTIFACT_DIR,artifact}=require('./config.cjs');
const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch();const p=await b.newPage({viewport:{width:1440,height:1100}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(BASE_URL);await p.waitForFunction(()=>!document.querySelector('#go').disabled);
const fixture=Buffer.from(await p.evaluate(()=>{const c=document.createElement('canvas');c.width=540;c.height=2200;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,540,2200);x.fillStyle='#222';x.font='22px sans-serif';x.fillText('Article preview',30,70);return c.toDataURL().split(',')[1];}),'base64');
const keys=['#url','#captureDetails','.formatbar','#go','main'];
for(const viewport of [{width:1440,height:1100},{width:390,height:844}]){await p.setViewportSize(viewport);assert(await p.locator('.stage-title').isHidden());assert(await p.locator('main').isHidden());assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:artifact(`newsgram-setup-${viewport.width}.png`),fullPage:true});}
let calls=0,params;await p.route('https://api.microlink.io/**',r=>{calls++;params=new URL(r.request().url()).searchParams;return r.fulfill({status:200,contentType:'image/png',body:fixture});});
await p.locator('#captureDetails summary').click();await p.locator('#width').selectOption('768');await p.locator('#area').selectOption('page');await p.locator('#stack').uncheck();await p.locator('#url').fill('https://example.com/article');await p.locator('#go').click();await p.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Captured'));assert.equal(params.get('viewport.width'),'768');assert.equal(params.get('screenshot.fullPage'),'true');assert(!params.has('styles'));assert.equal(await p.locator('#captureDetails').getAttribute('open'),null);await p.setViewportSize({width:1440,height:1100});await p.locator('#mobileSetup').click();const y=await p.evaluate(keys=>keys.map(k=>document.querySelector(k).getBoundingClientRect().top),keys);assert(y.every((v,i)=>!i||v>y[i-1]),JSON.stringify(y));assert(await p.locator('.stage-title').isHidden());assert(await p.locator('#mobileSetup').isVisible());assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.locator('#mobileSetup').click();await p.setViewportSize({width:390,height:844});assert(await p.locator('main').isVisible());assert(await p.locator('.stage-title').isHidden());assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
const hash=await p.locator('#editorCanvas').evaluate(c=>c.toDataURL());await p.locator('#mobileSetup').click();await p.locator('#width').selectOption('540');assert(await p.locator('#captureChanges').isVisible());assert.equal(calls,1);assert.equal(await p.locator('#editorCanvas').evaluate(c=>c.toDataURL()),hash);
await p.locator('#width').selectOption('768');assert(await p.locator('#captureChanges').isHidden());await p.locator('[data-ratio="1:1"]').click();assert(await p.locator('#captureChanges').isHidden());assert.equal(calls,1);
assert.deepEqual(errors,[]);console.log('PASS: link → webpage settings → image shape → capture → framing, desktop/mobile; request settings applied; pending-settings notice; edits do not recapture.');await b.close();})().catch(e=>{console.error(e);process.exit(1)});
