const {BASE_URL,ARTIFACT_DIR,artifact}=require('./config.cjs');const {savedSource}=require('./helpers.cjs');
const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch();const p=await b.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true});await p.goto(BASE_URL);await p.waitForFunction(()=>!document.querySelector('#go').disabled);const data=await p.evaluate(()=>{const c=document.createElement('canvas');c.width=540;c.height=4000;return c.toDataURL().split(',')[1]});await p.locator('#file').setInputFiles({name:'touch.png',mimeType:'image/png',buffer:Buffer.from(data,'base64')});await p.waitForSelector('#editorCanvas',{state:'visible'});assert.equal(await p.locator('#zoom').getAttribute('min'),'1');await p.locator('#fitSource').click();assert.equal(await p.locator('#zoom').inputValue(),'17');await p.locator('#zoomPresets [data-zoom="50"]').click();assert.equal(await p.locator('#zoom').inputValue(),'50');await p.locator('#zoomPresets [data-zoom="150"]').click();assert.equal(await p.locator('#zoom').inputValue(),'150');assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.locator('#zoom').fill('100');await p.locator('#editorCanvas').scrollIntoViewIfNeeded();const cdp=await p.context().newCDPSession(p);
// A real touch-pointer stroke on a phone-sized canvas is saved in source coordinates.
await p.locator('#dockMark').click();await p.locator('#editorCanvas').scrollIntoViewIfNeeded();const mr=await p.locator('#editorCanvas').boundingBox(),mx=mr.x+mr.width*.18,my=mr.y+mr.height*.18;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:mx,y:my}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:mx+mr.width*.55,y:my+mr.height*.01}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(await p.locator('#undoStroke').isDisabled(),false);const touchMarks=await savedSource(p);assert.equal(touchMarks.highlights[0].marks.length,1);assert.equal(touchMarks.highlights[0].marks[0].color,'#ffe45b');await p.locator('#undoStroke').click();assert.equal(await p.locator('#clearMarks').isHidden(),true);await p.locator('#dockMark').click();
await p.locator('#editorCanvas').scrollIntoViewIfNeeded();const panRect=await p.locator('#editorCanvas').boundingBox(),panx=panRect.x+panRect.width/2,pany=panRect.y+150;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:panx,y:pany}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:panx,y:pany-60}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.waitForTimeout(100);assert(+await p.locator('#position').inputValue()>0);await p.locator('#dockUndo').click();assert.equal(await p.locator('#position').inputValue(),'0');
await p.locator('#dockAdd').click();await p.locator('#thumbStrip').scrollIntoViewIfNeeded();const ids=()=>p.locator('.thumb').evaluateAll(ns=>ns.map(n=>n.dataset.id)),before=await ids();const g1=await p.locator('.grip').first().boundingBox(),g2=await p.locator('.grip').nth(1).boundingBox();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:g1.x+8,y:g1.y+8}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:g2.x+8,y:g2.y+8}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.deepEqual(await ids(),before.reverse());
await p.locator('#dockCut').click();await p.locator('#cutTop').fill('450');await p.locator('#cutBottom').fill('700');await p.locator('#editorCanvas').scrollIntoViewIfNeeded();
const cutRect=await p.locator('#editorCanvas').boundingBox(),tx=cutRect.x+cutRect.width*.3,ty=cutRect.y+cutRect.height*.08;
await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:tx,y:ty}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:tx,y:cutRect.y+cutRect.height*.25}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
assert(Math.abs(+await p.locator('#cutTop').inputValue()-108)<4);assert(Math.abs(+await p.locator('#cutBottom').inputValue()-338)<4);
const bottomHandle=await p.locator('[data-edge="bottom"]').boundingBox();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:bottomHandle.x+15,y:bottomHandle.y+15}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:bottomHandle.x+15,y:bottomHandle.y+45}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert(+await p.locator('#cutBottom').inputValue()>360);
await p.locator('#applyCut').click();assert.equal(await p.locator('#editCuts').textContent(),'1 section cut · Edit');await p.locator('#dockUndo').click();assert(await p.locator('#editCuts').isHidden());
console.log('PASS: phone-size Fit/preset zoom, touch drawing and stroke undo, touch panning, reordering, band selection and cut-handle dragging.');
await b.close();})().catch(e=>{console.error(e);process.exit(1)});
