"""Embed the pinned PDF.js distribution in index.html (no runtime CDN/server dependency).
Install development package: npm ci
Run from project folder: python3 tools/embed-pdf.py /path/to/node_modules/pdfjs-dist
"""
from pathlib import Path
import base64, gzip, json, re, sys, html, subprocess
project=Path(__file__).resolve().parent.parent
root=Path(sys.argv[1]).resolve() if len(sys.argv)>1 else project/'node_modules/pdfjs-dist'
assert json.loads((root/'package.json').read_text())['version']=='5.4.624'
# Classic, statically embedded factory scripts avoid import(blob:...) and eval.
# They initialize lazily. The worker factory also supports PDF.js's in-page fallback.
esbuild=root.parent/'esbuild'
def classic(entry,name):
    # Use esbuild's JS API: its installed bin may be a native executable on Unix
    # and a launcher on Windows, so it cannot reliably be invoked with `node bin`.
    script="const r=require(process.argv[1]).buildSync({entryPoints:[process.argv[2]],bundle:true,format:'iife',globalName:process.argv[3],target:'es2020',minify:true,legalComments:'inline',external:['node:*'],write:false});process.stdout.write(r.outputFiles[0].text);"
    result=subprocess.run(['node','-e',script,str(esbuild),str(root/entry),name],
        check=True,capture_output=True,text=True,encoding='utf-8')
    return result.stdout.replace('</script',r'<\/script')
main=classic('legacy/build/pdf.mjs','NewsGramPdfLib')
worker=classic('legacy/build/pdf.worker.mjs','NewsGramPdfWorker')
bundle={'version':'5.4.624'}
for folder,ext in [('standard_fonts',None),('cmaps','.bcmap'),('wasm','.wasm')]:
    bundle[folder]={f.name:base64.b64encode(f.read_bytes()).decode() for f in sorted((root/folder).iterdir()) if not f.name.startswith('LICENSE') and (ext is None or f.suffix==ext)}
encoded=base64.b64encode(gzip.compress(json.dumps(bundle,separators=(',',':')).encode(),compresslevel=9,mtime=0)).decode()
licenses=[]
for f in [root/'LICENSE',*(root/'standard_fonts').glob('LICENSE*'),root/'cmaps/LICENSE',*(root/'wasm').glob('LICENSE*')]:
    licenses.append(str(f.relative_to(root))+'\n'+f.read_text())
license_text='PDF.js 5.4.624 and bundled font, CMap and image-decoder assets.\nDistribution JavaScript is bundled to classic ES2020 IIFEs with esbuild for loader compatibility.\nNo PDF rendering logic is intentionally changed; application integration is NewsGram code.\n\n'+'\n\n'.join(licenses)
markup=('<!-- BEGIN EMBEDDED PDF ENGINE: generated by tools/embed-pdf.py -->\n'
    '<script id="pdfRuntime">globalThis.newsgramPdfLibrary=function(){'+main+';return NewsGramPdfLib;};</script>\n'
    '<script id="pdfWorkerRuntime">globalThis.newsgramPdfWorker=function(){'+worker+';return NewsGramPdfWorker;};</script>\n'
    '<script id="pdfBundle" type="application/octet-stream">'+encoded+'</script>\n'
    '<!-- END EMBEDDED PDF ENGINE -->')
p=project/'index.html';s=p.read_text(encoding='utf-8')
pattern=r'<!-- BEGIN EMBEDDED PDF ENGINE[\s\S]*?<!-- END EMBEDDED PDF ENGINE -->'
if re.search(pattern,s):
    s=re.sub(pattern,lambda _:markup,s)
else:
    s=s.replace('</body>',markup+'\n</body>')
s=re.sub(r'(<pre id="pdfLicenseText">)[\s\S]*?(</pre>)',lambda m:m[1]+html.escape(license_text)+m[2],s)
p.write_text(s,encoding='utf-8')
(project/'PDF-THIRD-PARTY-NOTICES.txt').write_text(license_text,encoding='utf-8')
print(f'Embedded PDF engine: {len(encoded):,} base64 characters; HTML: {p.stat().st_size:,} bytes')
